- name: Set fact for citrixAdmAgent tempdir
  set_fact:
    citrixAdmAgentTempDir: "/tmp/citrixAdmAgent-{{ ansible_date_time.iso8601_basic_short }}"
  tags:
    - citrixAdmAgent

- name: Get citrix-adm-agent secret from KeyVault
  shell: "az keyvault secret show --vault kv-{{ environmentShort }}-{{ locationShort }}-{{ configuration.coreResourceGroupName }} --name citrix-adm-agent --output json"
  register: citrixAdmAgentSecret
  tags:
    - citrixAdmAgent

- name: Set Citrix ADM Agent facts
  set_fact:
    citrixAdmAgentConfig:
      secret:
        db_key_conf: "{{ ((citrixAdmAgentSecret.stdout | from_json).value | from_json).secret.db_key_conf }}"
        private_pem: "{{ ((citrixAdmAgentSecret.stdout | from_json).value | from_json).secret.private_pem }}"
        public_pem: "{{ ((citrixAdmAgentSecret.stdout | from_json).value | from_json).secret.public_pem }}"
        password: "{{ ((citrixAdmAgentSecret.stdout | from_json).value | from_json).secret.password }}"
      configmap:
        agent_conf: "{{ ((citrixAdmAgentSecret.stdout | from_json).value | from_json).configmap.agent_conf | b64decode }}"
        proxy_conf: "{{ ((citrixAdmAgentSecret.stdout | from_json).value | from_json).configmap.proxy_conf | b64decode }}"
  tags:
    - citrixAdmAgent

- name: Download and apply helm template
  block:
    - name: Create citrixAdmAgent temp dir
      file:
        path: "{{ citrixAdmAgentTempDir }}"
        state: directory
        mode: 0755
      changed_when: false
      tags:
        - citrixAdmAgent

    - name: Add citrixAdmAgent namespace
      k8s:
        kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ configuration.citrixAdmAgent.namespace }}"
            labels: "{{ configuration.citrixAdmAgent.labels | combine({'name': configuration.citrixAdmAgent.namespace}) }}"
      when: configuration.citrixAdmAgent.state == "present"
      tags:
        - citrixAdmAgent

    - name: Create Kubernetes secret for citirx-adm-agent
      k8s:
        kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
        state: "{{ configuration.citrixAdmAgent.state }}"
        namespace: "{{ configuration.citrixAdmAgent.namespace }}"
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: citrix-adm-agent
          data:
            db_key.conf: "{{ citrixAdmAgentConfig.secret.db_key_conf }}"
            private.pem: "{{ citrixAdmAgentConfig.secret.private_pem }}"
            public.pem: "{{ citrixAdmAgentConfig.secret.public_pem }}"
            password: "{{ citrixAdmAgentConfig.secret.password }}"
      tags:
        - citrixAdmAgent

    - name: Create Kubernetes configmap for citrix-adm-agent
      k8s:
        kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
        state: "{{ configuration.citrixAdmAgent.state }}"
        namespace: "{{ configuration.citrixAdmAgent.namespace }}"
        definition:
          kind: ConfigMap
          apiVersion: v1 
          metadata:
            name: citrix-adm-agent
          data:
            agent.conf: |
              {{ citrixAdmAgentConfig.configmap.agent_conf }}
            proxy.conf: |
              {{ citrixAdmAgentConfig.configmap.proxy_conf }}
      tags:
        - citrixAdmAgent

    - name: Helm repo add citrix-helm-charts
      shell: "{{ helm.binDir }}/helmv3 repo add citrix-helm-charts https://xenitab.github.io/citrix-helm-charts/"
      tags:
        - citrixAdmAgent

    - name: Helm repo update
      shell: "{{ helm.binDir }}/helmv3 repo update"
      tags:
        - citrixAdmAgent

    - name: Install citrixAdmAgent
      shell: '{{ helm.binDir }}/helmv3 --kubeconfig="{{ configuration.k8sconfiguration.dest }}" upgrade --wait --install --version {{ configuration.citrixAdmAgent.helmChartVersion }} --namespace {{ configuration.citrixAdmAgent.namespace }} {{ configuration.citrixAdmAgent.helmChartName }} citrix-helm-charts/citrix-adm-agent'
      register: citrixAdmAgentInstallResult
      when: configuration.citrixAdmAgent.state == "present"
      tags:
        - citrixAdmAgent

    - name: Restart citrixAdmAgent deployment
      shell: '{{ kubectl.bin_directory }}/kubectl --kubeconfig="{{ configuration.k8sconfiguration.dest }}" --namespace={{ configuration.citrixAdmAgent.namespace }} rollout restart deployment {{ configuration.citrixAdmAgent.helmChartName }}'
      when: configuration.citrixAdmAgent.state == "present"
      tags:
        - citrixAdmAgent

    - name: Remove citrixAdmAgent
      shell: '{{ helm.binDir }}/helmv3 --kubeconfig="{{ configuration.k8sconfiguration.dest }}" --namespace {{ configuration.citrixAdmAgent.namespace }} uninstall {{ configuration.citrixAdmAgent.helmChartName }}'
      when: configuration.citrixAdmAgent.state == "absent"
      tags:
        - citrixAdmAgent

    - name: Remove citrixAdmAgent namespace
      k8s:
        kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ configuration.citrixAdmAgent.namespace }}"
      when: configuration.citrixAdmAgent.state == "absent"
      tags:
        - citrixAdmAgent

    - name: Delete temporary local folder
      file:
        path: "{{ citrixAdmAgentTempDir }}/"
        state: absent
      changed_when: false
      tags:
        - citrixAdmAgent

  rescue:
    - name: Delete temporary local folder
      file:
        path: "{{ citrixAdmAgentTempDir }}/"
        state: absent
      changed_when: false
      tags:
        - citrixAdmAgent

    - name: Fail task
      fail:
        msg: "Rescue was invoked, task failed."
      tags:
        - citrixAdmAgent
