- name: Set fact for externalDns tempdir
  set_fact:
    externalDnsTempDir: "/tmp/externalDns-{{ ansible_date_time.iso8601_basic_short }}"
  tags:
    - externalDns

- name: Get dns-secret secret from KeyVault
  shell: "az keyvault secret show --vault kv-{{ environmentShort }}-{{ locationShort }}-{{ configuration.coreResourceGroupName }} --name dns-secret --output json"
  register: externalDnsSecret
  tags:
    - externalDns

- name: Set facts for externalDns-api-key
  set_fact:
    externalDnsApiKey: "{{ (externalDnsSecret.stdout | from_json).value }}"
  tags:
    - externalDns

- name: Download and apply helm template
  block:
    - name: Create externalDns temp dir
      file:
        path: "{{ externalDnsTempDir }}"
        state: directory
        mode: 0755
      changed_when: false
      tags:
        - externalDns

    - name: Add externalDns namespace
      k8s:
        kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ configuration.externalDns.namespace }}"
            labels: "{{ configuration.externalDns.labels | combine({'name': configuration.externalDns.namespace}) }}"
      when: configuration.externalDns.state == "present"
      tags:
        - externalDns

    - name: Copy externalDns-values.yaml.j2 manifest jinja2 templates
      template:
        src: "externalDns-values.yaml.j2"
        dest: "{{ externalDnsTempDir }}/externalDns-values.yaml"
      changed_when: false
      tags:
        - externalDns

    - name: Helm repo add bitnami
      shell: "{{ helm.binDir }}/helmv3 repo add bitnami https://charts.bitnami.com/bitnami"
      tags:
        - externalDns

    - name: Helm repo update
      shell: "{{ helm.binDir }}/helmv3 repo update"
      tags:
        - externalDns

    - name: Install externalDns
      shell: '{{ helm.binDir }}/helmv3 -f {{ externalDnsTempDir }}/externalDns-values.yaml --kubeconfig="{{ configuration.k8sconfiguration.dest }}" upgrade --wait --install --version {{ configuration.externalDns.helmChartVersion }} --namespace {{ configuration.externalDns.namespace }} {{ configuration.externalDns.helmChartName }} bitnami/external-dns'
      register: externalDnsInstallResult
      when: configuration.externalDns.state == "present"
      tags:
        - externalDns

    - name: Restart externalDns deployment
      shell: '{{ kubectl.bin_directory }}/kubectl --kubeconfig="{{ configuration.k8sconfiguration.dest }}" --namespace={{ configuration.externalDns.namespace }} delete pods -l app={{ configuration.externalDns.helmChartName }}'
      when: configuration.externalDns.state == "present"
      tags:
        - externalDns

    - name: Remove externalDns
      shell: '{{ helm.binDir }}/helmv3 --kubeconfig="{{ configuration.k8sconfiguration.dest }}" --namespace {{ configuration.externalDns.namespace }} uninstall {{ configuration.externalDns.helmChartName }}'
      when: configuration.externalDns.state == "absent"
      tags:
        - externalDns

    - name: Remove externalDns namespace
      k8s:
        kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ configuration.externalDns.namespace }}"
      when: configuration.externalDns.state == "absent"
      tags:
        - externalDns

    - name: Delete temporary local folder
      file:
        path: "{{ externalDnsTempDir }}/"
        state: absent
      changed_when: false
      tags:
        - externalDns

  rescue:
    - name: Delete temporary local folder
      file:
        path: "{{ externalDnsTempDir }}/"
        state: absent
      changed_when: false
      tags:
        - externalDns

    - name: Fail task
      fail:
        msg: "Rescue was invoked, task failed."
      tags:
        - externalDns
