- name: Set python interpreter if using Azure DevOps
  set_fact:
    ansible_python_interpreter: "{{ adoAnsiblePythonInterpreter }}"
  when: adoAnsiblePythonInterpreter is defined
  tags:
    - common

- name: Create variable for temp_folder
  set_fact:
    temp_folder: "{{lookup('env', 'TMPDIR') | default('/tmp', true)}}/{{ lookup('env', 'USER') }}"
  tags:
    - common

- name: Creates temp_folder if it doesn't exists
  file:
    path: "{{ temp_folder }}"
    state: directory
  tags:
    - common

- name: Include variables for Kubernetes
  include_vars: "kubernetes-{{ environmentShort }}.yml"
  tags:
    - common

- name: Include variables for Kubernetes - common
  include_vars: "kubernetes-common.yml"
  tags:
    - common

- name: Set playbook facts
  set_fact:
    resourceGroupName: "rg-{{ environmentShort }}-{{ locationShort }}-{{ aksCommonName }}"
  tags:
    - common

- name: AKS List Cluster Admin Credential
  azure_rm_resource:
    resource_group: "{{ resourceGroupName }}"
    provider: ContainerService
    resource_type: managedClusters
    resource_name: "aks-{{ environmentShort }}-{{ locationShort }}-{{ commonName }}/listClusterAdminCredential"
    api_version: "2018-03-31"
    method: POST
  register: clusterUserCredential
  changed_when: false
  tags:
    - common

- name: Run playbook
  block:
    - name: Fetch k8s configuration
      copy:
        content: "{{ clusterUserCredential.response.kubeconfigs[0].value | b64decode }}"
        dest: "{{ configuration.k8sconfiguration.dest }}"
      changed_when: false
      tags:
        - common

    - name: Include kubectl.yml
      include_tasks: kubectl.yml
      tags:
        - kubectl

    - name: Include helm.yml
      include_tasks: helm.yml
      tags:
        - helm

    - name: Include helmv3.yml
      include_tasks: helmv3.yml
      tags:
        - helmv3

    - name: Include externalDns.yml
      include_tasks: externalDns.yml
      when: configuration.externalDns.enabled
      tags:
        - externalDns

    - name: Include certManager.yml
      include_tasks: certManager.yml
      when: configuration.certManager.enabled
      tags:
        - certManager

    - name: Include opaGatekeeper.yml
      include_tasks: opaGatekeeper/opaGatekeeper.yml
      when: configuration.opaGatekeeper.enabled
      tags:
        - opaGatekeeper

    - name: Include dhkeyOperator.yml
      include_tasks: dhkeyOperator.yml
      when: configuration.dhkeyOperator.enabled
      tags:
        - dhkeyOperator

    - name: Include citrixAdmAgent.yml
      include_tasks: citrixAdmAgent.yml
      when: configuration.citrixAdmAgent.enabled
      tags:
        - citrixAdmAgent

    - name: Include citrixCpx.yml
      include_tasks: citrixCpx.yml
      when: configuration.citrixCpx.enabled
      tags:
        - citrixCpx

    - name: Include velero.yml
      include_tasks: velero.yml
      when: configuration.velero.enabled
      tags:
        - velero

    - name: Include datadog.yml
      include_tasks: datadog.yml
      when: configuration.datadog.enabled
      tags:
        - datadog

    - name: Include dnsTxtRecords.yml
      include_tasks: dnsTxtRecords.yml
      when: configuration.dnsTxtRecords.enabled
      tags:
        - dnsTxtRecords

    - name: Include ingressNginx.yml
      include_tasks: ingressNginx.yml
      when: configuration.ingressNginx.enabled
      tags:
        - ingressNginx

    - name: Remove k8s configuration
      file:
        state: absent
        path: "{{ configuration.k8sconfiguration.dest }}"
      changed_when: false
      tags:
        - common

  rescue:
    - name: Remove k8s configuration
      file:
        state: absent
        path: "{{ configuration.k8sconfiguration.dest }}"
      changed_when: false
      tags:
        - common

    - name: Fail task
      fail:
        msg: "Rescue was invoked, task failed."
      tags:
        - common
