- name: Check OS
  shell: uname
  register: unameResult
  tags:
    - helmv3

- name: Download helm v3 archive - Linux
  get_url:
    url: "https://get.helm.sh/helm-{{ helmv3.version }}-{{ unameResult.stdout | lower }}-amd64.tar.gz"
    checksum: "{{ helmv3.checksumLinux }}"
    dest: "{{ helmv3.tmpDir }}"
  when:
    - (unameResult.stdout | lower) == "linux"
  tags:
    - helmv3

- name: Download helm v3 archive - Mac
  get_url:
    url: "https://get.helm.sh/helm-{{ helmv3.version }}-{{ unameResult.stdout | lower }}-amd64.tar.gz"
    checksum: "{{ helmv3.checksumMac }}"
    dest: "{{ helmv3.tmpDir }}"
  when:
    - (unameResult.stdout | lower) == "darwin"
  tags:
    - helmv3

- name: Create helm v3 directory
  file:
    path: "{{ helmv3.tmpDir }}/helm-{{ helmv3.version }}"
    state: directory
    mode: 0755
  tags:
    - helmv3

- name: Unarchive helm v3
  unarchive:
    src: "{{ helmv3.tmpDir }}/helm-{{ helmv3.version }}-{{ unameResult.stdout | lower }}-amd64.tar.gz"
    dest: "{{ helmv3.tmpDir }}/helm-{{ helmv3.version }}"
  tags:
    - helmv3

- name: Copy helm v3 binary to destination directory
  copy:
    src: "{{ helmv3.tmpDir }}/helm-{{ helmv3.version }}/{{ unameResult.stdout | lower }}-amd64/helm"
    dest: "{{ helmv3.binDir }}/helmv3"
    mode: 0755
  tags:
    - helmv3
