parameters:
  jobName: ""
  vmImage: ""
  environment: ""

jobs:
- job: ${{ parameters.jobName }}
  condition: and(succeeded(), eq(variables['${{ parameters.environment }}EnvEnabled'], true))
  displayName: Build ${{ parameters.environment }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  continueOnError: false
  steps:      
  - task: AzureCLI@1
    displayName: 'Build task'
    inputs:
      azureSubscription: 'azure-tflab-${{ parameters.environment }}-owner'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        cd $(workingDirectory)
        if [[ $opaBlastRadius == ?(-)+([0-9]) ]]; then
          blastRadius=$opaBlastRadius
        else
          blastRadius=""
        fi
        pwsh .ci/Invoke-PipelineTask.ps1 -tfFolderName '$(tfFolderName)' -azureDevOps -build -tfVersion $(tfVersion) -environmentShort ${{ parameters.environment }} -artifactPath '$(Build.ArtifactStagingDirectory)' ${blastRadius:+ -opaBlastRadius $blastRadius}
    env:
      tfEncPassword: $(terraformEncryptionSecret)
      opaBlastRadius: $(opaBlastRadius)
  
  - task: PublishPipelineArtifact@0
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Publish artifact'
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: '${{ parameters.environment }}'