parameters:
  deployment: ""
  vmImage: ""
  environment: ""

jobs:
- deployment: ${{ parameters.deployment }}
  displayName: Deploy to ${{ parameters.environment }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  continueOnError: false
  environment: ${{ parameters.environment }}
  strategy: 
    runOnce:
      deploy:
        steps:
        - checkout: self
          displayName: Get sources

        - task: DownloadPipelineArtifact@2
          displayName: 'Download artifact'
          inputs:
            artifact: '${{ parameters.environment }}'
            path: '$(System.ArtifactsDirectory)'
            
        - task: AzureCLI@1
          displayName: 'Deploy task'
          inputs:
            azureSubscription: 'azure-aks-${{ parameters.environment }}-owner'
            addSpnToEnvironment: true
            scriptLocation: inlineScript
            inlineScript: |
              cd $(workingDirectory)
              pwsh .ci/Invoke-PipelineTask.ps1 -tfFolderName '$(tfFolderName)' -azureDevOps -deploy -tfVersion $(tfVersion) -environmentShort ${{ parameters.environment }} -artifactPath '$(System.ArtifactsDirectory)'
          env:
            tfEncPassword: $(terraformEncryptionSecret)