stages:
- stage: Build
  jobs:
  - template: build.yml
    parameters:
      jobName: Build_dev
      vmImage: $(vmImage)
      environment: dev
      
  - template: build.yml
    parameters:
      jobName: Build_qa
      vmImage: $(vmImage)
      environment: qa

  - template: build.yml
    parameters:
      jobName: Build_prod
      vmImage: $(vmImage)
      environment: prod

- stage: Deploy_dev
  condition: and(succeeded(), eq(variables['devEnvEnabled'], true), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: [Build]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_dev
      vmImage: $(vmImage)
      environment: dev

- stage: Deploy_qa
  condition: and(succeeded(), eq(variables['qaEnvEnabled'], true), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: [Deploy_dev]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_qa
      vmImage: $(vmImage)
      environment: qa

- stage: Deploy_prod
  condition: and(succeeded(), eq(variables['prodEnvEnabled'], true), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: [Deploy_qa]
  jobs:
  - template: deploy.yml
    parameters:
      deployment: Deploy_prod
      vmImage: $(vmImage)
      environment: prod