variables:
  - group: terraform-encryption
  - name: workingDirectory
    value: azure/terraform/examples
  - name: devEnvEnabled
    value: true
  - name: qaEnvEnabled
    value: false
  - name: prodEnvEnabled
    value: false
  - name: tfVersion
    value: "0.12.26"
  - name: vmImage
    value: "ubuntu-latest"
  - name: tfFolderName
    value: "tf-boilerplate"

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - azure/terraform/examples/tf-boilerplate

# In Azure DevOps this doesn't work yet - you need to add it using branch policies: https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation
pr:
  branches:
    include:
      - master
  paths:
    include:
      - azure/terraform/examples/tf-boilerplate

stages:
  - template: templates/pipeline.yml
