variables:
  - name: vmImage
    value: "ubuntu-latest"
  - name: workingDirectory
    value: aws/ansible/configure-eks
  - name: devEnvEnabled
    value: true
  - name: qaEnvEnabled
    value: false
  - name: prodEnvEnabled
    value: false
  - name: awsRegion
    value: 'eu-north-1'

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - aws/ansible/configure-eks

pr: none

stages:
  - template: templates/pipeline.yml
