- name: Manage a k8s Cluster Role Bindings - cluster-admin
  k8s:
    kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "crb-cluster-admin"
      subjects:
        - kind: Group
          name: "cluster-admin"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: "cluster-admin"
        apiGroup: rbac.authorization.k8s.io
  tags:
    - k8s

- name: Manage a k8s Cluster Role Bindings - cluster-viewer
  k8s:
    kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "crb-cluster-viewer"
      subjects:
        - kind: Group
          name: "cluster-viewer"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: "view"
        apiGroup: rbac.authorization.k8s.io
  tags:
    - k8s
