variables:
  - name: workingDirectory
    value: azure/ansible/configure-aks
  - name: vmImage
    value: "ubuntu-latest"
  - name: devEnvEnabled
    value: true
  - name: qaEnvEnabled
    value: false
  - name: prodEnvEnabled
    value: false

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - azure/ansible/configure-aks

pr: none

stages:
  - template: templates/pipeline.yml
